# Jupyter Book Configuration
title: "Big Data Analytics"
author: "Dr. Chebil Khalil"
logo: images/logo.png
copyright: "2025"

execute:
  execute_notebooks: cache
  timeout: 300
  allow_errors: false

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

latex:
  latex_documents:
    targetname: bigdata_analytics.tex

bibtex_bibfiles:
  - appendix/references.bib

repository:
  url: https://github.com/chebil/BigData
  path_to_book: ""
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  baseurl: https://chebil.github.io/BigData/

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
    - sphinx_design
    - sphinx_copybutton
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/chebil/BigData
      use_repository_button: true
      use_issues_button: true
      use_download_button: true
